{
 "title": "Kafka queue size",
 "description": "Shows sizes of these queues over time",
 "tags": [ "kafka" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partitions,topic)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset,instance)"
    }
   },
   {
    "name": "ConsumerGroup",
    "label": "ConsumerGroup",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{topic=\"$Topic\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TopicOffset",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\",instance=\"[[Instance]]\"}) by (topic,consumergroup)",
     "legendFormat": "{{topic}} {{consumergroup}}"
    }
   ]
  },
  {
   "title": "ConsumerGroupLAG",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"$Topic\",consumergroup=~\"$ConsumerGroup\",instance=~\"$Instance\"}) by(topic,consumergroup)",
     "legendFormat": "{{topic}} {{consumergroup}}"
    }
   ]
  },
  {
   "title": "MessagesIn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_topic_partition_current_offset{topic=\"$Topic\",instance=~\"$Instance\"}[1m]))",
     "legendFormat": "{{topic}} {{partition}}"
    }
   ]
  },
  {
   "title": "MessagesOut",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{topic=\"[[Topic]]\",consumergroup=\"[[ConsumerGroup]]\",instance=\"[[Instance]]\"}[1m])) by (topic,consumergroup)",
     "legendFormat": "{{topic}} {{consumergroup}}"
    }
   ]
  }
 ]
}