apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-consumer
  namespace: demo
spec:
  scaleTargetRef:
    name: consumer  # Replace with your deployment name
  triggers:
    - type: kafka
      metadata:
        activationLagThreshold: "10"
        bootstrapServers: keda-demo-kafka-bootstrap.strimzi-system.svc:9092  # Replace with your Kafka broker list
        topic: demo  # Replace with your Kafka topic
        consumerGroup: my-consumer-group  # Replace with your consumer group
        consumerOffset: latest  # Replace with the desired consumer offset
        lagTreshold: "1000"
        maxReplicaCount: "10"  # Maximum number of replicas
        minReplicaCount: "0"  # Min number of replicas