builds:
  - id: consumer
    main: ./consumer
    binary: consumer
    tags:
      - release
      - embed_frontend
    env:
      - VERSION="development"
      - GO_VERSION="1.22"
      - CGO_ENABLED=0
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - linux
    # We currently cannot run mysqlbinlog on arm64.
    goarch:
      - amd64
      - arm64
  - id: producer
    main: ./producer
    binary: producer
    tags:
      - release
    env:
      - VERSION="development"
      - GO_VERSION="1.22"
      - CGO_ENABLED=0
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - linux
    # We currently cannot run mysqlbinlog on arm64.
    goarch:
      - amd64
      - arm64
