builds:
  - id: consumer
    main: ./consumer
    binary: consumer
    ldflags:
      - -w -s
    tags:
      - release
      - embed_frontend
    env:
      - VERSION="development"
      - GO_VERSION="1.23"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - linux
    # We currently cannot run mysqlbinlog on arm64.
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
  - id: producer
    main: ./producer
    binary: producer
    ldflags:
      - -w -s
    tags:
      - release
    env:
      - VERSION="development"
      - GO_VERSION="1.23"
      - CGO_ENABLED=1
      - GIT_COMMIT="unknown"
      - BUILD_TIME="unknown"
      - BUILD_USER="unknown"
    goos:
      - linux
    # We currently cannot run mysqlbinlog on arm64.
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
